title: "League of Legends Role Analysis"
email: "your-email@example.com"
description: "Analyzing the impact of roles in League of Legends esports matches."
baseurl: ""
url: "https://hassam303.github.io/League-of-Legends-Role-Analysis"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
